# Test case 1 in pdm4ar_scvxx
agents:
  PDM4ARSpaceship: # do not change this name
    state:
      x: -8.0
      y: -8.0
      psi: 0.26179938779 
      vx: 0.0
      vy: 0.0
      dpsi: 0.0
      delta: 0.0
      m: 2.5
    goal:
      type: dock
      state: 
        x: 8.0
        y: 8.0
        psi: 3.8
        vx: 0.0
        vy: 0.0
        dpsi: 0.0
      pos_tolerance: 0.7
      dir_tolerance: 0.5
      vel_tolerance: 0.3
      add_land_space: 0.0 
      arms_length: 0.7
      offset: 1.2
    color: 'blue'

planets:
  Namek:
    center: [40.0, 40.0]
    radius: 2.5
    satellites: {}

boundary:
  corners:
    - [-11, -11]
    - [-11, 11]
    - [11, 11]
    - [11, -11]
    - [-11, -11]

seed: 98